# Generated by Django 2.0.9 on 2018-10-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181022_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='tags',
            field=models.ManyToManyField(null=True, to='core.Tag'),
        ),
    ]
