# Generated by Django 2.0.9 on 2018-10-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181022_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='core.Tag'),
        ),
    ]
